# Generated by Django 3.1.5 on 2021-03-11 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fast_online_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='Телефон')),
                ('date', models.DateTimeField(verbose_name='Дата и время праздника')),
                ('number_children', models.CharField(default='', max_length=50, verbose_name='Колличество детей')),
                ('hero', models.CharField(default='', max_length=50, verbose_name='Герой')),
                ('time', models.CharField(default='', max_length=50, verbose_name='Длительность программы')),
            ],
            options={
                'verbose_name': 'Быстрый заказ',
                'verbose_name_plural': 'Быстрые заказы',
            },
        ),
        migrations.CreateModel(
            name='our_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(blank=True, upload_to='static/data_for_project/img/img_gallery', verbose_name='Изображение')),
                ('date_event', models.DateTimeField(verbose_name='Дата и время события')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('u_surname', models.CharField(default='', max_length=50, verbose_name='Фамилия')),
                ('review', models.TextField(verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default='', max_length=50, verbose_name='Услуги')),
                ('img_service1', models.ImageField(blank=True, upload_to='static/data_for_project/img/img_goods', verbose_name='Изображение услуги')),
                ('img_service2', models.ImageField(blank=True, upload_to='static/data_for_project/img/img_goods', verbose_name='Изображение услуги')),
                ('img_service3', models.ImageField(blank=True, upload_to='static/data_for_project/img/img_goods', verbose_name='Изображение услуги')),
                ('service_name', models.CharField(default='', max_length=50, verbose_name='Название услуги')),
                ('service_description', models.TextField(verbose_name='Описание услуг')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='service_cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.TextField(verbose_name='Название услуги')),
                ('service_cost_min', models.TextField(verbose_name='Стоимость 30мин')),
                ('service_cost_base', models.TextField(verbose_name='Стоимость 60мин')),
                ('service_cost_max', models.TextField(verbose_name='Стоимость 90мин')),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_for_project.service')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
