# Generated by Django 3.1.5 on 2021-03-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_for_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='img_service1',
            field=models.ImageField(blank=True, upload_to='img/img_goods', verbose_name='Изображение услуги'),
        ),
    ]
